version: '3'

services:
  database:
    image: 'mysql:5'
    environment:  
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DB} 
    ports:
      - '23306:3306'
    env_file:
      - .env
    networks:
      - mysql-network
    
networks: 
  mysql-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1