version: '3'

services:
  database:
    image: 'mysql:5'
    environment:  
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DB} 
    ports:
      - '23306:3306'
    env_file:
      - .env
    networks:
      - mysql-network
    
networks: 
  mysql-network:
    driver: bridge